### ISSUE TITLE
assert pattern.endswith("?") builtins.AssertionError: 

### ISSUE THREAD

**Issue by rohandosi** [andyalam/django_ig#3]
Hey andyalam,
I am facing this issue after cloning and running your project. Can you please help me out?

env/lib/python3.6/site-packages/asgi_redis/core.py", line 269, in new_channel     assert pattern.endswith("?") builtins.AssertionError:

**Comment by andyalam** [comment]
@rohandosi Can you post a more detailed error log?

**Comment by rohandosi** [comment]
@andyalam : Here is a more detailed error log. Could you please have a look:


Unhandled Error
Traceback (most recent call last):
  File "/Users/Rohan/Desktop/new_django-insta/env/lib/python3.6/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/Rohan/Desktop/new_django-insta/env/lib/python3.6/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/Rohan/Desktop/new_django-insta/env/lib/python3.6/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/Rohan/Desktop/new_django-insta/env/lib/python3.6/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/Rohan/Desktop/new_django-insta/env/lib/python3.6/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/Rohan/Desktop/new_django-insta/env/lib/python3.6/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/Users/Rohan/Desktop/new_django-insta/env/lib/python3.6/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/Rohan/Desktop/new_django-insta/env/lib/python3.6/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/Users/Rohan/Desktop/new_django-insta/env/lib/python3.6/site-packages/twisted/web/http.py", line 1701, in lineReceived
    request = self.requestFactory(self, len(self.requests))
  File "/Users/Rohan/Desktop/new_django-insta/env/lib/python3.6/site-packages/daphne/http_protocol.py", line 50, in __init__
    self.reply_channel = self.factory.channel_layer.new_channel("http.response!")
  File "/Users/Rohan/Desktop/new_django-insta/env/lib/python3.6/site-packages/asgi_redis/core.py", line 269, in new_channel
    assert pattern.endswith("?")
builtins.AssertionError:

**Comment by andyalam** [comment]
Do you have Redis running on port 6379? I have a sentence on it in the README but it's not that clear. Settings for the port if you want it changed can be found in the settings.py file. 

If you're running Linux [here's](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-redis-on-ubuntu-16-04) a decent tutorial for Ubuntu.

**Comment by rohandosi** [comment]
@andyalam, Yes i have Redis up and running on port 6379. I still cant figure out what the error is about. Do you have any idea?

**Comment by andyalam** [comment]
No clue, I'll leave this open for a while incase anyone else stumbles upon similar issues.

**Comment by rohandosi** [comment]
@andyalam Sure, that would be great. Thanks.

**Comment by sah-anshu** [comment]
Unhandled Error
Traceback (most recent call last):
  File "/test/Projects/django_instagram/venv/lib/python3.5/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/test/Projects/django_instagram/venv/lib/python3.5/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/test/Projects/django_instagram/venv/lib/python3.5/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/test/Projects/django_instagram/venv/lib/python3.5/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/test/Projects/django_instagram/venv/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/test/Projects/django_instagram/venv/lib/python3.5/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/test/Projects/django_instagram/venv/lib/python3.5/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/test/Projects/django_instagram/venv/lib/python3.5/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/test/Projects/django_instagram/venv/lib/python3.5/site-packages/twisted/web/http.py", line 1701, in lineReceived
    request = self.requestFactory(self, len(self.requests))
  File "/test/Projects/django_instagram/venv/lib/python3.5/site-packages/daphne/http_protocol.py", line 50, in __init__
    self.reply_channel = self.factory.channel_layer.new_channel("http.response!")
  File "/test/Projects/django_instagram/venv/lib/python3.5/site-packages/asgi_redis/core.py", line 225, in new_channel
    assert pattern.endswith("?")
builtins.AssertionError:
