### ISSUE TITLE
...base_layer.py", line 34, in receive_many     raise NotImplementedError()

### ISSUE THREAD

**Issue by skyler14** [andyalam/django_ig#7]
When I try and run your example I upon doing 

`python manage.py runworker`

```
2019-10-26 18:17:48,242 - INFO - runworker - Using single-threaded worker.
2019-10-26 18:17:48,242 - INFO - runworker - Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)
2019-10-26 18:17:48,242 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/skyler/Documents/pyvenvs/insta-django/lib/python3.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/skyler/Documents/pyvenvs/insta-django/lib/python3.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/skyler/Documents/pyvenvs/insta-django/lib/python3.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/skyler/Documents/pyvenvs/insta-django/lib/python3.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/skyler/Documents/pyvenvs/insta-django/lib/python3.7/site-packages/channels/management/commands/runworker.py", line 82, in handle
    worker.run()
  File "/home/skyler/Documents/pyvenvs/insta-django/lib/python3.7/site-packages/channels/worker.py", line 88, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/home/skyler/Documents/pyvenvs/insta-django/lib/python3.7/site-packages/asgiref/base_layer.py", line 34, in receive_many
    raise NotImplementedError()
NotImplementedError
```
I tried running regis server and with regis-cli i got a ping back on the right port.

**Comment by skyler14** [comment]
python manage.py runserver --noworker
outputs in case it helped
```
October 26, 2019 - 18:17:40
Django version 1.10.3, using settings 'django_ig.settings'
Starting Channels development server at http://127.0.0.1:8000/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CONTROL-C. 
```
